[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "alembic>=1.16.5",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.116.2",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.43",
    "supabase>=2.20.0",
    "uvicorn>=0.35.0",
    "youtube-transcript-api>=1.2.2",
    "yt-dlp>=2025.9.23",
]
