"use client";

import { useState, useRef, useEffect } from "react";

export default function Hero() {
  const [sliderPosition, setSliderPosition] = useState(50);
  const containerRef = useRef<HTMLDivElement>(null);
  const isDragging = useRef(false);

  const handleMouseDown = () => {
    isDragging.current = true;
  };

  const handleMouseUp = () => {
    isDragging.current = false;
  };

  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!isDragging.current || !containerRef.current) return;

    const rect = containerRef.current.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const percentage = (x / rect.width) * 100;
    setSliderPosition(Math.min(Math.max(percentage, 0), 100));
  };

  const handleTouchMove = (e: React.TouchEvent<HTMLDivElement>) => {
    if (!containerRef.current) return;

    const rect = containerRef.current.getBoundingClientRect();
    const x = e.touches[0].clientX - rect.left;
    const percentage = (x / rect.width) * 100;
    setSliderPosition(Math.min(Math.max(percentage, 0), 100));
  };

  useEffect(() => {
    const handleGlobalMouseUp = () => {
      isDragging.current = false;
    };

    window.addEventListener("mouseup", handleGlobalMouseUp);
    return () => window.removeEventListener("mouseup", handleGlobalMouseUp);
  }, []);

  return (
    <section className="grid grid-cols-1 items-center gap-12 md:grid-cols-2 md:gap-16">
      {/* Left Content */}
      <div className="flex flex-col items-start gap-6 text-left">
        <h1 className="text-4xl font-bold leading-tight tracking-tighter sm:text-5xl md:text-6xl">
          AI Thumbnails That Get Views.
        </h1>
        <h2 className="max-w-md text-base font-normal leading-normal text-muted-foreground sm:text-lg">
          Instantly generate stunning YouTube thumbnails from your video content
          and boost your engagement.
        </h2>
        <button className="flex min-w-[84px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-12 px-6 bg-primary text-primary-foreground text-base font-bold leading-normal tracking-wide transition-opacity hover:opacity-90">
          <span className="truncate">Generate My Thumbnail Now</span>
        </button>
      </div>

      {/* Right Content - Image Slider */}
      <div
        ref={containerRef}
        className="relative w-full aspect-[4/3] overflow-hidden rounded-xl border border-border select-none"
        onMouseMove={handleMouseMove}
        onMouseUp={handleMouseUp}
        onMouseLeave={handleMouseUp}
        onTouchMove={handleTouchMove}
      >
        {/* Before Image (Background) */}
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{
            backgroundImage:
              'url("https://lh3.googleusercontent.com/aida-public/AB6AXuB47y1ham7dJ4Iv3513Q89bFxtGAikj22afsUQDiWAtKwBv2xy-eQvU0vTChGOLpqslXPE1g5CoiksSdxhNnLvqWxIiXTLdmrVvbdrm7KDcDs_vOflmz-LKTTVtiTWNxR4DBFNd3E7GAmIPfOn5K2buqEc0kZOqSFv6-HsmbsiZ-mQIjJIQJIKu5Z4DScBlu9oCqyKLipa2jeijJAX88Nspl2RGMZ_mblw9FMSOGwzoGoM7Jq0hA1Izu3ws1q63DtcjeFeJzV950Kk")',
          }}
          aria-label="A dull, unedited frame from a video about cryptocurrency, showing a simple chart."
        />

        {/* After Image (Overlay) */}
        <div
          className="absolute inset-0 overflow-hidden"
          style={{ width: `${sliderPosition}%` }}
        >
          <div
            className="absolute inset-0 h-full w-full bg-cover bg-center"
            style={{
              backgroundImage:
                'url("https://lh3.googleusercontent.com/aida-public/AB6AXuAg5aFMbn9EynsnHbnUEutMCPTst12cn2neMM2kAshg2gqRX0hbwMQvD74VQZBu4NNmnviCkI5G6RhaR8JNjJoHhzyGnHnb1bkIZSMHDjDtmymEkh7ZdlFF93Mys3yDwsA59nQ6C4nDTZnT2KZrbWrfkgSnjh4_cs2c7cdJ0cJJSBd_R_bQqPimF090sh13_0jENc72GKs_xeUzNNXGWTXhkcjIRtLwUtSb5n4f57UzrZISVQ1kgP16GcBYqcU0z1PLeGOxxwcM1Jg")',
              width: `${(100 / sliderPosition) * 100}%`,
            }}
            aria-label="A vibrant, attention-grabbing YouTube thumbnail for a cryptocurrency video, with bold text and graphics, generated by Firenail."
          />

          {/* Slider Handle */}
          <div
            className="absolute bottom-0 right-0 top-0 w-1 cursor-ew-resize bg-primary/50"
            onMouseDown={handleMouseDown}
            onTouchStart={handleMouseDown}
          >
            <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary p-1 text-primary-foreground">
              <svg
                className="h-4 w-4"
                fill="none"
                stroke="currentColor"
                strokeWidth="3"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M8 9l4-4 4 4m0 6l-4 4-4-4"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
