"""Initial migration with profiles and images tables

Revision ID: 22e51114cfdd
Revises: 
Create Date: 2025-09-27 21:11:17.267989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22e51114cfdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('video_title', sa.String(), nullable=True),
    sa.Column('video_summary', sa.Text(), nullable=True),
    sa.Column('crawled_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_image_storage_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_images_profile_created', 'images', ['profile_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    
    # Enable Row Level Security (RLS) on profiles table
    op.execute("ALTER TABLE profiles ENABLE ROW LEVEL SECURITY")
    
    # Enable RLS on images table
    op.execute("ALTER TABLE images ENABLE ROW LEVEL SECURITY")
    
    # Create RLS policy for profiles - users can only see/modify their own profile
    op.execute("""
        CREATE POLICY "Users can view own profile" ON profiles
        FOR SELECT USING (auth.uid() = id)
    """)
    
    op.execute("""
        CREATE POLICY "Users can insert own profile" ON profiles
        FOR INSERT WITH CHECK (auth.uid() = id)
    """)
    
    op.execute("""
        CREATE POLICY "Users can update own profile" ON profiles
        FOR UPDATE USING (auth.uid() = id)
    """)
    
    # Create RLS policy for images - users can only see/modify their own images
    op.execute("""
        CREATE POLICY "Users can view own images" ON images
        FOR SELECT USING (auth.uid() = profile_id)
    """)
    
    op.execute("""
        CREATE POLICY "Users can insert own images" ON images
        FOR INSERT WITH CHECK (auth.uid() = profile_id)
    """)
    
    op.execute("""
        CREATE POLICY "Users can update own images" ON images
        FOR UPDATE USING (auth.uid() = profile_id)
    """)
    
    op.execute("""
        CREATE POLICY "Users can delete own images" ON images
        FOR DELETE USING (auth.uid() = profile_id)
    """)
    
    # Create function to handle new user registration
    op.execute("""
        CREATE OR REPLACE FUNCTION public.handle_new_user()
        RETURNS trigger AS $$
        BEGIN
            INSERT INTO public.profiles (id, username, avatar_url)
            VALUES (
                new.id,
                new.raw_user_meta_data->>'username',
                new.raw_user_meta_data->>'avatar_url'
            );
            RETURN new;
        END;
        $$ LANGUAGE plpgsql SECURITY definer;
    """)
    
    # Create trigger that calls the function when a new user is created
    op.execute("""
        CREATE TRIGGER on_auth_user_created
        AFTER INSERT ON auth.users
        FOR each ROW EXECUTE PROCEDURE public.handle_new_user();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop trigger and function first
    op.execute("DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users")
    op.execute("DROP FUNCTION IF EXISTS public.handle_new_user()")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_profile_created', table_name='images')
    op.drop_table('images')
    op.drop_table('profiles')
    # ### end Alembic commands ###
