"""removed transcript col from video table

Revision ID: 273dbe6f0d5f
Revises: 018d58e3fe7a
Create Date: 2025-10-11 22:49:28.546603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273dbe6f0d5f'
down_revision: Union[str, Sequence[str], None] = '018d58e3fe7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'transcript')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
