"""Add Job, Video, JobEvent models and relationships

Revision ID: 392e04d439f5
Revises: 22e51114cfdd
Create Date: 2025-09-28 16:31:58.889025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '392e04d439f5'
down_revision: Union[str, Sequence[str], None] = '22e51114cfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('youtube_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('images', sa.Column('job_id', sa.UUID(), nullable=False))
    op.add_column('images', sa.Column('keywords', sa.JSON(), nullable=False))
    op.add_column('images', sa.Column('firecrawl_payload', sa.JSON(), nullable=True))
    op.add_column('images', sa.Column('storage_public_url', sa.Text(), nullable=True))
    op.alter_column('images', 'id', server_default=None)
    op.alter_column('images', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='gen_random_uuid()')
    op.alter_column('images', 'id', server_default=sa.text('gen_random_uuid()'))
    op.drop_index(op.f('ix_images_profile_created'), table_name='images')
    op.create_foreign_key(None, 'images', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_column('images', 'video_title')
    op.drop_column('images', 'video_summary')
    op.drop_column('images', 'crawled_images')
    op.drop_column('images', 'generated_image_storage_urls')
    # Enable RLS and create policies
    op.execute("ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY jobs_policy ON jobs FOR ALL USING (user_id = auth.uid());")
    op.execute("ALTER TABLE images ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY images_policy ON images FOR ALL USING (profile_id = auth.uid());")
    op.execute("ALTER TABLE videos ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY videos_policy ON videos FOR ALL USING (EXISTS (SELECT 1 FROM jobs WHERE jobs.id = videos.job_id AND jobs.user_id = auth.uid()));")
    op.execute("ALTER TABLE job_events ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY job_events_policy ON job_events FOR ALL USING (EXISTS (SELECT 1 FROM jobs WHERE jobs.id = job_events.job_id AND jobs.user_id = auth.uid()));")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('generated_image_storage_urls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('crawled_images', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('video_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('video_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_index(op.f('ix_images_profile_created'), 'images', ['profile_id', 'created_at'], unique=False)
    op.alter_column('images', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('images', 'storage_public_url')
    op.drop_column('images', 'firecrawl_payload')
    op.drop_column('images', 'keywords')
    op.drop_column('images', 'job_id')
    op.drop_table('videos')
    op.drop_table('job_events')
    op.drop_table('jobs')
    # ### end Alembic commands ###
