"""removed video_id from video tabl

Revision ID: a2d5c906f79b
Revises: d6e887ad4570
Create Date: 2025-11-04 11:34:13.872216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d5c906f79b'
down_revision: Union[str, Sequence[str], None] = 'd6e887ad4570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'youtube_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('youtube_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
