"""add_video_title_to_image_model

Revision ID: cdc1c53fbe4a
Revises: 53e008946c54
Create Date: 2025-10-16 16:29:32.738808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc1c53fbe4a'
down_revision: Union[str, Sequence[str], None] = '53e008946c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('video_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'video_title')
    # ### end Alembic commands ###
