"""added limits to user profile

Revision ID: d6e887ad4570
Revises: fc038eecc6e0
Create Date: 2025-10-29 16:55:29.858017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e887ad4570'
down_revision: Union[str, Sequence[str], None] = 'fc038eecc6e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('images_generated', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('profiles', sa.Column('period_reset_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.add_column('subscriptions', sa.Column('images_generated', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('subscriptions', sa.Column('period_reset_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'period_reset_at')
    op.drop_column('subscriptions', 'images_generated')
    op.drop_column('profiles', 'period_reset_at')
    op.drop_column('profiles', 'images_generated')
    # ### end Alembic commands ###
