"""update_storage_url_type_to_json_list

Revision ID: e86043bfcf82
Revises: a2d5c906f79b
Create Date: 2025-12-01 22:14:02.076422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86043bfcf82'
down_revision: Union[str, Sequence[str], None] = 'a2d5c906f79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'storage_public_url',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               postgresql_using="CASE WHEN storage_public_url IS NULL THEN '[]'::json ELSE json_build_array(storage_public_url) END")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'storage_public_url',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
